spring:
  application:
    name: booking-service
  datasource: #Database configuration
    url: ${DB_URL:jdbc:postgresql://localhost:15442/postgres} #IF DB_URL is passed as env variable, it will be used, or the one after the (Colon - :)
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  rabbitmq: #RabbitMQ Configuration
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  jpa:
    open-in-view: false

server:
  port: 8082
  shutdown: graceful

#Booking Queue names configuration for RabbitMQ
bookings:
  movie-service-url: "http://localhost:8081"         #Movie service url for interservice communication
  bookings-events-exchange: "bookings-exchange"
  new-bookings-queue: "new-bookings"
  successful-bookings-queue: "successful-bookings"
  cancelled-bookings-queue: "cancelled-bookings"
  error-bookings-queue: "error-bookings"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    git:
      mode: "full"