CREATE TABLE booking_events (
    id SERIAL PRIMARY KEY NOT NULL,
    event_id VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);