spring:
  application:
    name: movie-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:15432/postgres} #IF DB_URL is passed as env variable, it will be used, or the one after the (Colon - :)
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

server:
  port: 8081
  shutdown: graceful


management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    git:
      mode: "full"


dummy:
  text: "This is dummy line."